// 官方 JS ↔ native 命令码表（98 条）。
//
// 来源：游戏底包 assets/package/web/test/config.js —— f4samurai 留下的开发测试页的
// 一部分，同目录的 command.html / touch2.html / command.js 是能跑的测试台。
// 本文件由脚本从该 config.js 生成，请勿手改；换底包后重新生成并比对差异。
//
// 命令码是引擎与元游戏前端之间的私有约定，官方没有兼容性承诺——底包一换就可能变。
//
// 分段（段内留有空洞，是官方预留）：
//   <100     数据与设备      100-199  音效
//   200-399  场景切换        400-499  显示与演出
//   500-599  本地通知        600+     显示与演出（续）

/** 命令码 -> 官方常量名 */
export const OFFICIAL_COMMAND_NAMES: Readonly<Record<number, string>> = Object.freeze({
  1: "DATA_CLEAR_WEB_CACHE",
  2: "DATA_REMOVE_ASSET",
  5: "DATA_CALL_TOUCHES_BEGIN",
  6: "DATA_CALL_TOUCHES_MOVE",
  7: "DATA_CALL_TOUCHES_END",
  10: "DATA_AWAKE_PURCHASE",
  11: "DATA_PURCHASE_ITEM",
  12: "DATA_GET_PURCHASE_STATE",
  20: "DATA_GET_SNS_USER_ID",
  21: "DATA_GET_APP_VERSION",
  22: "DATA_GET_DOWNLOAD_CONFIG",
  23: "DATA_GET_DEVICE_INFO",
  25: "DATA_CLOSE_APP",
  30: "DATA_GET_FONT",
  40: "DATA_GET_QUEST_RESULT_JSON",
  50: "DATA_OPEN_URL",
  60: "DATA_GET_BASE64",
  62: "DATA_SET_CLIPBOARD",
  70: "DATA_GET_REWARD",
  71: "DATA_DELETE_REWARD",
  90: "DATA_OPEN_EDIT_BOX",
  95: "DATA_GET_QUEST_REPLAY_DATA_ID",
  96: "DATA_DELETE_QUEST_REPLAY_DATA",
  97: "DATA_GET_QUEST_REPLAY_VERSION",
  100: "SOUND_BGM_PLAY",
  101: "SOUND_BGM_STOP",
  102: "SOUND_BGM_RESUME",
  103: "SOUND_BGM_PAUSE",
  104: "SOUND_BGM_SET_VOL",
  105: "SOUND_BGM_GET_VOL",
  110: "SOUND_SE_PLAY",
  111: "SOUND_SE_STOP",
  114: "SOUND_SE_SET_VOL",
  115: "SOUND_SE_GET_VOL",
  120: "SOUND_VO_PLAY",
  121: "SOUND_VO_STOP",
  124: "SOUND_VO_SET_VOL",
  125: "SOUND_VO_GET_VO",
  201: "SCENE_PUSH_WEBVIEW",
  202: "SCENE_POP_WEBVIEW",
  211: "SCENE_PUSH_LOADING",
  221: "SCENE_PUSH_DOWNLOAD",
  231: "SCENE_PUSH_GACHA",
  241: "SCENE_PUSH_EVOLUTION",
  251: "SCENE_PUSH_MEMORIA_COMPOSE",
  261: "SCENE_PUSH_STORY",
  271: "SCENE_PUSH_QUEST",
  272: "SCENE_POP_QUEST",
  275: "SCENE_PUSH_QUEST_REPLAY",
  276: "SCENE_SEND_QUEST_REPLAY_DATA",
  281: "SCENE_PUSH_ARENA",
  282: "SCENE_POP_ARENA",
  291: "SCENE_PUSH_CHAT",
  292: "SCENE_POP_CHAT",
  301: "SCENE_PUSH_TOP",
  302: "SCENE_POP_TOP",
  341: "SCENE_PUSH_ANOTHER_QUEST",
  342: "SCENE_POP_ANOTHER_QUEST",
  343: "SCENE_PLAY_ANOTHER_QUEST",
  351: "SCENE_PUSH_MOVIE",
  361: "SCENE_PUSH_MOVIE_CHAR",
  371: "SCENE_PUSH_EVENT_TEST",
  400: "DISPLAY_SET_WEBVIEW_VISIBLE",
  410: "DISPLAY_CHANGE_BG",
  420: "DISPLAY_ADD_L2D",
  421: "DISPLAY_REMOVE_L2D",
  422: "DISPLAY_PALY_L2D_MOTION",
  430: "DISPLAY_ADD_MINI",
  431: "DISPLAY_REMOVE_MINI",
  432: "DISPLAY_PLAY_MINI_MOTION",
  433: "DISPLAY_PLAY_MINI_EFFECT",
  434: "DISPLAY_STOP_MINI_EFFECT",
  440: "DISPLAY_ADD_MOVIE",
  450: "DISPLAY_PLAY_COMPOSE_EFFECT",
  451: "DISPLAY_SHOW_COMPOSE_RESULT",
  452: "DISPLAY_HIDE_COMPOSE",
  460: "DISPLAY_PLAY_COMPOSE_MAGIA",
  465: "DISPLAY_PLAY_AWAKE_ABILITY",
  470: "DISPLAY_PLAY_NORMAL_GACHA_TOP",
  471: "DISPLAY_STOP_NORMAL_GACHA_TOP",
  490: "DISPLAY_PLAY_MEMORIA_TOP",
  491: "DISPLAY_STOP_MEMORIA_TOP",
  500: "NOTI_GET_CONF_PNOTE",
  501: "NOTI_AWAKE_PNOTE",
  502: "NOTI_TURN_ON_PNOTE",
  503: "NOTI_TURN_OFF_PNOTE",
  510: "NOTI_GET_CONF_WEEKLY_QUEST",
  511: "NOTI_TURN_ON_WEEKLY_QUEST",
  512: "NOTI_TURN_OFF_WEEKLY_QUEST",
  520: "NOTI_GET_CONF_AP_FULL",
  521: "NOTI_TURN_ON_AP_FULL",
  522: "NOTI_TURN_OFF_AP_FULL",
  600: "DISPLAY_PLAY_FORMATION",
  601: "DISPLAY_STOP_FORMATION",
  610: "DISPLAY_PLAY_WEEKLY_QUEST_TOP",
  611: "DISPLAY_STOP_WEEKLY_QUEST_TOP",
  620: "DISPLAY_PLAY_FORMATION_ENEMY",
  621: "DISPLAY_STOP_FORMATION_ENEMY",
});

/** 官方常量名 -> 命令码 */
export const OFFICIAL_COMMAND_CODES: Readonly<Record<string, number>> = Object.freeze(
  Object.fromEntries(
    Object.entries(OFFICIAL_COMMAND_NAMES).map(([code, name]) => [name, Number(code)]),
  ),
);

/** 已知命令码总数，用于自检。 */
export const OFFICIAL_COMMAND_COUNT = 98;

